stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dbd.sh
      pushRemote: true
      registry: registry.dbd.sh
  when:
    branch:
      include:
      - master
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch: {}
notification: {}
