stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dbd.sh
      registry: 127.0.0.1:34756
  when:
    branch:
      include:
      - master
- name: deploy
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: echo "Hello World"
timeout: 60
branch: {}
notification: {}
