stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dbdaniel/dbd.sh:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dbdaniel/dbd.sh:latest
      pushRemote: true
      registry: index.docker.io
  when:
    branch:
      include:
      - master
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch: {}
notification: {}
