apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbd-sh
spec:
  selector:
    matchLabels:
      app: dbd-sh
  replicas: 1 
  template:
    metadata:
      labels:
        app: dbd-sh
    spec:
      containers:
      - name: dbd-sh
        image: dbd.sh
        ports:
        - containerPort: 20300
          protocol: TCP
